apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
{{- if .Values.annotations }}
  annotations: 
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ include "zookeeper.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{ if .Values.client.internalDnsName }}
  annotations:
    dns.alpha.kubernetes.io/internal: {{ .Values.client.internalDnsName }}
    service.beta.kubernetesion.io/aws-load-balancer-internal: {{ .Values.client.awsLoadBalancerInternal }}
  {{ end }}
spec:
  {{ if .Values.client.internalDnsName  }}type: "LoadBalancer"{{ else }}type: {{ .Values.client.type }} {{ end }}
  ports:
  - port: {{ .Values.client.port }}
    name: client
  selector:
    app: {{ include "zookeeper.name" . | quote }}
    release: {{ .Release.Name | quote }}
{{- if .Values.serviceType }}
  type: {{ .Values.serviceType }}
{{- end }}

