dependencies:
- name: postgresql
  version: ~0.8.10
  repository: https://pgalchemy.github.io/charts/
  condition: postgresql.enabled
- name: cassandra
  version: ~0.1.0
  repository: https://pgalchemy.github.io/charts/
  condition: cassandra.enabled
